server:
  port: 8010
spring:
  application:
    name: samheos-things
  cloud:
    nacos:
      username: nacos
      password: Laidor010714
      server-addr: 106.14.107.236:8848
      discovery:
        namespace: samheos-cloud
      config:
        namespace: samheos-cloud
        file-extension: yml
        shared-configs:
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}