server:
  port: 8080
spring:
  application:
    name: samheos-gateway
  cloud:
    nacos:
      username: nacos
      password: Laidor010714
      server-addr: 106.14.107.236:8848
      discovery:
        namespace: samheos-cloud
      config:
        namespace: samheos-cloud
        file-extension: yml
    gateway:
      routes:
        - id: samheos-things
          uri: lb://samheos-things
          predicates:
            - Path=/things/**
#          filters:
#            - StripPrefix=1
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}